export interface Book {
  id: number;
  name: string;
  englishName: string;
  chapters: number;
  filename: string;
  testament?: 'OT' | 'NT';
}

export const books: Book[] = [
  { id: 0, name: "उत्पत्ति", englishName: "Genesis", chapters: 50, filename: "GEN.json", testament: 'OT' },
  { id: 1, name: "प्रस्थान", englishName: "Exodus", chapters: 40, filename: "EXO.json", testament: 'OT' },
  { id: 2, name: "लेवीहरू", englishName: "Leviticus", chapters: 27, filename: "LEV.json", testament: 'OT' },
  { id: 3, name: "गन्ती", englishName: "Numbers", chapters: 36, filename: "NUM.json", testament: 'OT' },
  { id: 4, name: "व्यवस्था", englishName: "Deuteronomy", chapters: 34, filename: "DEU.json", testament: 'OT' },
  { id: 5, name: "यहोशू", englishName: "Joshua", chapters: 24, filename: "JOS.json", testament: 'OT' },
  { id: 6, name: "न्यायकर्ताहरू", englishName: "Judges", chapters: 21, filename: "JDG.json", testament: 'OT' },
  { id: 7, name: "रूथ", englishName: "Ruth", chapters: 4, filename: "RUT.json", testament: 'OT' },
  { id: 8, name: "१ शमूएल", englishName: "1 Samuel", chapters: 31, filename: "1SA.json", testament: 'OT' },
  { id: 9, name: "२ शमूएल", englishName: "2 Samuel", chapters: 24, filename: "2SA.json", testament: 'OT' },
  { id: 10, name: "१ राजाहरू", englishName: "1 Kings", chapters: 22, filename: "1KI.json", testament: 'OT' },
  { id: 11, name: "२ राजाहरू", englishName: "2 Kings", chapters: 25, filename: "2KI.json", testament: 'OT' },
  { id: 12, name: "१ इतिहास", englishName: "1 Chronicles", chapters: 29, filename: "1CH.json", testament: 'OT' },
  { id: 13, name: "२ इतिहास", englishName: "2 Chronicles", chapters: 36, filename: "2CH.json", testament: 'OT' },
  { id: 14, name: "एज्रा", englishName: "Ezra", chapters: 10, filename: "EZR.json", testament: 'OT' },
  { id: 15, name: "नहेम्याह", englishName: "Nehemiah", chapters: 13, filename: "NEH.json", testament: 'OT' },
  { id: 16, name: "एस्तर", englishName: "Esther", chapters: 10, filename: "EST.json", testament: 'OT' },
  { id: 17, name: "अय्यूब", englishName: "Job", chapters: 42, filename: "JOB.json", testament: 'OT' },
  { id: 18, name: "भजनसंग्रह", englishName: "Psalms", chapters: 150, filename: "PSA.json", testament: 'OT' },
  { id: 19, name: "हितोपदेश", englishName: "Proverbs", chapters: 31, filename: "PRO.json", testament: 'OT' },
  { id: 20, name: "उपदेशक", englishName: "Ecclesiastes", chapters: 12, filename: "ECC.json", testament: 'OT' },
  { id: 21, name: "श्रेष्ठगीत", englishName: "Song of songs", chapters: 8, filename: "SNG.json", testament: 'OT' },
  { id: 22, name: "यशैया", englishName: "Isaiah", chapters: 66, filename: "ISA.json", testament: 'OT' },
  { id: 23, name: "यर्मिया", englishName: "Jeremiah", chapters: 52, filename: "JER.json", testament: 'OT' },
  { id: 24, name: "विलाप", englishName: "Lamentations", chapters: 5, filename: "LAM.json", testament: 'OT' },
  { id: 25, name: "इजकिएल", englishName: "Ezekiel", chapters: 48, filename: "EZK.json", testament: 'OT' },
  { id: 26, name: "दानिएल", englishName: "Daniel", chapters: 12, filename: "DAN.json", testament: 'OT' },
  { id: 27, name: "होशे", englishName: "Hosea", chapters: 14, filename: "HOS.json", testament: 'OT' },
  { id: 28, name: "योएल", englishName: "Joel", chapters: 3, filename: "JOL.json", testament: 'OT' },
  { id: 29, name: "आमोस", englishName: "Amos", chapters: 9, filename: "AMO.json", testament: 'OT' },
  { id: 30, name: "ओबदिया", englishName: "Obadiah", chapters: 1, filename: "OBA.json", testament: 'OT' },
  { id: 31, name: "योना", englishName: "Jonah", chapters: 4, filename: "JON.json", testament: 'OT' },
  { id: 32, name: "मीका", englishName: "Micah", chapters: 7, filename: "MIC.json", testament: 'OT' },
  { id: 33, name: "नहूम", englishName: "Nahum", chapters: 3, filename: "NAM.json", testament: 'OT' },
  { id: 34, name: "हबकूक", englishName: "Habakkuk", chapters: 3, filename: "HAB.json", testament: 'OT' },
  { id: 35, name: "सपन्याह", englishName: "Zephaniah", chapters: 3, filename: "ZEP.json", testament: 'OT' },
  { id: 36, name: "हाग्गै", englishName: "Haggai", chapters: 2, filename: "HAG.json", testament: 'OT' },
  { id: 37, name: "जकरिया", englishName: "Zechariah", chapters: 14, filename: "ZEC.json", testament: 'OT' },
  { id: 38, name: "मलाकी", englishName: "Malachi", chapters: 4, filename: "MAL.json", testament: 'OT' },
  { id: 39, name: "मत्ती", englishName: "Matthew", chapters: 28, filename: "MAT.json", testament: 'NT' },
  { id: 40, name: "मर्कूस", englishName: "Mark", chapters: 16, filename: "MRK.json", testament: 'NT' },
  { id: 41, name: "लूका", englishName: "Luke", chapters: 24, filename: "LUK.json", testament: 'NT' },
  { id: 42, name: "यूहन्ना", englishName: "John", chapters: 21, filename: "JHN.json", testament: 'NT' },
  { id: 43, name: "प्रेरित", englishName: "Acts", chapters: 28, filename: "ACT.json", testament: 'NT' },
  { id: 44, name: "रोमी", englishName: "Romans", chapters: 16, filename: "ROM.json", testament: 'NT' },
  { id: 45, name: "१ कोरिन्थी", englishName: "1 Corinthians", chapters: 16, filename: "1CO.json", testament: 'NT' },
  { id: 46, name: "२ कोरिन्थी", englishName: "2 Corinthians", chapters: 13, filename: "2CO.json", testament: 'NT' },
  { id: 47, name: "गलाती", englishName: "Galatians", chapters: 6, filename: "GAL.json", testament: 'NT' },
  { id: 48, name: "एफिसी", englishName: "Ephesians", chapters: 6, filename: "EPH.json", testament: 'NT' },
  { id: 49, name: "फिलिप्पी", englishName: "Philippians", chapters: 4, filename: "PHP.json", testament: 'NT' },
  { id: 50, name: "कलस्सी", englishName: "Colossians", chapters: 4, filename: "COL.json", testament: 'NT' },
  { id: 51, name: "१ थेसलोनिकी", englishName: "1 Thessalonians", chapters: 5, filename: "1TH.json", testament: 'NT' },
  { id: 52, name: "२ थेसलोनिकी", englishName: "2 Thessalonians", chapters: 3, filename: "2TH.json", testament: 'NT' },
  { id: 53, name: "१ तिमोथी", englishName: "1 Timothy", chapters: 6, filename: "1TI.json", testament: 'NT' },
  { id: 54, name: "२ तिमोथी", englishName: "2 Timothy", chapters: 4, filename: "2TI.json", testament: 'NT' },
  { id: 55, name: "तीतस", englishName: "Titus", chapters: 3, filename: "TIT.json", testament: 'NT' },
  { id: 56, name: "फिलेमोन", englishName: "Philemon", chapters: 1, filename: "PHM.json", testament: 'NT' },
  { id: 57, name: "हिब्रू", englishName: "Hebrews", chapters: 13, filename: "HEB.json", testament: 'NT' },
  { id: 58, name: "याकूब", englishName: "James", chapters: 5, filename: "JAS.json", testament: 'NT' },
  { id: 59, name: "१ पत्रुस", englishName: "1 Peter", chapters: 5, filename: "1PE.json", testament: 'NT' },
  { id: 60, name: "२ पत्रुस", englishName: "2 Peter", chapters: 3, filename: "2PE.json", testament: 'NT' },
  { id: 61, name: "१ यूहन्ना", englishName: "1 John", chapters: 5, filename: "1JN.json", testament: 'NT' },
  { id: 62, name: "२ यूहन्ना", englishName: "2 John", chapters: 1, filename: "2JN.json", testament: 'NT' },
  { id: 63, name: "३ यूहन्ना", englishName: "3 John", chapters: 1, filename: "3JN.json", testament: 'NT' },
  { id: 64, name: "यहूदा", englishName: "Jude", chapters: 1, filename: "JUD.json", testament: 'NT' },
  { id: 65, name: "प्रकाश", englishName: "Revelation", chapters: 22, filename: "REV.json", testament: 'NT' }
];
