export const books = [
  { id: 0, name: "उत्पत्ति", englishName: "Genesis", chapters: 50 },
  { id: 1, name: "प्रस्थान", englishName: "Exodus", chapters: 40 },
  { id: 2, name: "लेवी", englishName: "Leviticus", chapters: 27 },
  { id: 3, name: "गन्ती", englishName: "Numbers", chapters: 36 },
  { id: 4, name: "व्यवस्था", englishName: "Deuteronomy", chapters: 34 },
  { id: 5, name: "यहोशू", englishName: "Joshua", chapters: 24 },
  { id: 6, name: "न्यायकर्ता", englishName: "Judges", chapters: 21 },
  { id: 7, name: "रूथ", englishName: "Ruth", chapters: 4 },
  { id: 8, name: "१ शमूएल", englishName: "1 Samuel", chapters: 31 },
  { id: 9, name: "२ शमूएल", englishName: "2 Samuel", chapters: 24 },
  { id: 10, name: "१ राजा", englishName: "1 Kings", chapters: 22 },
  { id: 11, name: "२ राजा", englishName: "2 Kings", chapters: 25 },
  { id: 12, name: "१ इतिहास", englishName: "1 Chronicles", chapters: 29 },
  { id: 13, name: "२ इतिहास", englishName: "2 Chronicles", chapters: 36 },
  { id: 14, name: "एज्रा", englishName: "Ezra", chapters: 10 },
  { id: 15, name: "नहेम्याह", englishName: "Nehemiah", chapters: 13 },
  { id: 16, name: "एस्तर", englishName: "Esther", chapters: 10 },
  { id: 17, name: "अय्यूब", englishName: "Job", chapters: 42 },
  { id: 18, name: "भजनसंग्रह", englishName: "Psalms", chapters: 150 },
  { id: 19, name: "हितोपदेश", englishName: "Proverbs", chapters: 31 },
  { id: 20, name: "उपदेशक", englishName: "Ecclesiastes", chapters: 12 },
  { id: 21, name: "श्रेष्ठगीत", englishName: "Song of Solomon", chapters: 8 },
  { id: 22, name: "यशैया", englishName: "Isaiah", chapters: 66 },
  { id: 23, name: "यर्मिया", englishName: "Jeremiah", chapters: 52 },
  { id: 24, name: "विलापगीत", englishName: "Lamentations", chapters: 5 },
  { id: 25, name: "इजकिएल", englishName: "Ezekiel", chapters: 48 },
  { id: 26, name: "दानिएल", englishName: "Daniel", chapters: 12 },
  { id: 27, name: "होशे", englishName: "Hosea", chapters: 14 },
  { id: 28, name: "योएल", englishName: "Joel", chapters: 3 },
  { id: 29, name: "आमोस", englishName: "Amos", chapters: 9 },
  { id: 30, name: "ओबदिया", englishName: "Obadiah", chapters: 1 },
  { id: 31, name: "योना", englishName: "Jonah", chapters: 4 },
  { id: 32, name: "मीका", englishName: "Micah", chapters: 7 },
  { id: 33, name: "नहूम", englishName: "Nahum", chapters: 3 },
  { id: 34, name: "हबक्कूक", englishName: "Habakkuk", chapters: 3 },
  { id: 35, name: "सपन्याह", englishName: "Zephaniah", chapters: 3 },
  { id: 36, name: "हाग्गै", englishName: "Haggai", chapters: 2 },
  { id: 37, name: "जकरिया", englishName: "Zechariah", chapters: 14 },
  { id: 38, name: "मलाकी", englishName: "Malachi", chapters: 4 },
  { id: 39, name: "मत्ती", englishName: "Matthew", chapters: 28 },
  { id: 40, name: "मर्कूस", englishName: "Mark", chapters: 16 },
  { id: 41, name: "लूका", englishName: "Luke", chapters: 24 },
  { id: 42, name: "यूहन्ना", englishName: "John", chapters: 21 },
  { id: 43, name: "प्रेरित", englishName: "Acts", chapters: 28 },
  { id: 44, name: "रोमी", englishName: "Romans", chapters: 16 },
  { id: 45, name: "१ कोरिन्थी", englishName: "1 Corinthians", chapters: 16 },
  { id: 46, name: "२ कोरिन्थी", englishName: "2 Corinthians", chapters: 13 },
  { id: 47, name: "गलाती", englishName: "Galatians", chapters: 6 },
  { id: 48, name: "एफिसी", englishName: "Ephesians", chapters: 6 },
  { id: 49, name: "फिलिप्पी", englishName: "Philippians", chapters: 4 },
  { id: 50, name: "कलस्सी", englishName: "Colossians", chapters: 4 },
  { id: 51, name: "१ थिस्सलोनिकी", englishName: "1 Thessalonians", chapters: 5 },
  { id: 52, name: "२ थिस्सलोनिकी", englishName: "2 Thessalonians", chapters: 3 },
  { id: 53, name: "१ तिमोथी", englishName: "1 Timothy", chapters: 6 },
  { id: 54, name: "२ तिमोथी", englishName: "2 Timothy", chapters: 4 },
  { id: 55, name: "तीतस", englishName: "Titus", chapters: 3 },
  { id: 56, name: "फिलेमोन", englishName: "Philemon", chapters: 1 },
  { id: 57, name: "हिब्रू", englishName: "Hebrews", chapters: 13 },
  { id: 58, name: "याकूब", englishName: "James", chapters: 5 },
  { id: 59, name: "१ पत्रुस", englishName: "1 Peter", chapters: 5 },
  { id: 60, name: "२ पत्रुस", englishName: "2 Peter", chapters: 3 },
  { id: 61, name: "१ यूहन्ना", englishName: "1 John", chapters: 5 },
  { id: 62, name: "२ यूहन्ना", englishName: "2 John", chapters: 1 },
  { id: 63, name: "३ यूहन्ना", englishName: "3 John", chapters: 1 },
  { id: 64, name: "यहूदा", englishName: "Jude", chapters: 1 },
  { id: 65, name: "प्रकाश", englishName: "Revelation", chapters: 22 }
];
